# Generated by Django 3.1.6 on 2021-02-13 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=63, unique=True, verbose_name='Адрес электронной почты')),
                ('first_name', models.CharField(max_length=63, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=63, verbose_name='Фамилия')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('rating_points', models.IntegerField(default=0, verbose_name='Баллы')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('proof', models.FileField(blank=True, upload_to='', verbose_name='Файл, подтверждающий достижение')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтверждение')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Ценность')),
                ('judge', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_judge', to=settings.AUTH_USER_MODEL, verbose_name='Оцениватель')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
